const NEWS_TOP_K = 5

const NEWS_SEARCH_OVERFETCH_FACTOR = 4

const NEWS_MIN_SIMILARITY = 0.35

const NEWS_SIMILARITY_WEIGHT = 0.7
const NEWS_RECENCY_WEIGHT = 0.2
const NEWS_SOURCE_WEIGHT = 0.1
const NEWS_SECTION_WEIGHT = 0.05

const CHUNK_MAX_CHARS = 800
const CHUNK_OVERLAP_PARAGRAPHS = 1

const RECENCY_DECAY_DAYS = 30

module.exports = {
  NEWS_TOP_K,
  NEWS_SEARCH_OVERFETCH_FACTOR,
  NEWS_MIN_SIMILARITY,
  NEWS_SIMILARITY_WEIGHT,
  NEWS_RECENCY_WEIGHT,
  NEWS_SOURCE_WEIGHT,
  NEWS_SECTION_WEIGHT,
  CHUNK_MAX_CHARS,
  CHUNK_OVERLAP_PARAGRAPHS,
  RECENCY_DECAY_DAYS,
}
